### ISSUE TITLE
unexpected error when minimised

### ISSUE THREAD

**Issue by stvndall** [xolarity/WinGrooves#32] opened 2014-11-22 14:23 UTC
When the app tries to  take a screen grab and there are no bounds by which to grab from.

**Comment by SamPlusPlus** [comment] 2015-01-20 22:49
Looks like my code from https://github.com/xolarity/WinGrooves/pull/15 maybe I can take a look at it. Can you provide me some more details. What OS are you running? What version of IE do you have installed. Did you only have to minimize, or did you have to do anything else.

Basically the more info you can provide me to quickly reproduce this the faster I can look into it.

**Comment by stvndall** [comment] 2015-01-21 08:15
Hi There Sam, 

Look it seems to happen when and if it chooses, from what I can tell it's normally when it is in tray mode, I am in windows 8.1.

From what I can tell it just seems to throw some sort of exception when it is trying to get the bounds of that box.

I have seen some strange timing issues before were I think it tried to grab from the screen mid transition stage, because the thumbnail will become a view of my screen.

I'm not sure if this helps too much, Hope it does.
Thanks :)

**Comment by SamPlusPlus** [comment] 2015-01-22 04:44
@stvndall thanks for your feedback. I have submitted a purposed fixed. Hopefully @xolarity will merge it in and release a new build.

**Comment by xolarity** [comment] 2015-01-23 01:31
Thanks, @SamPlusPlus ! I merged that in and published a new build. People might need to manually install the new version because I had to use a new code signing certificate.

**Closed by xolarity** 2015-01-23 01:31 UTC
